// This file is automatically generated. Do not edit it directly.
// NOTE: This is being migrated to use custom API client
// For now, providing a stub to prevent errors during migration
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'http://localhost';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'dummy-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// NOTE: This is a stub - migrate to use api from '@/lib/api' instead

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});